api/urls.py
from django.urls import path

from . import views

app_name = 'api'

urlpatterns = [
    path('fetch', views.fetch, name='fetch'),
    path('update', views.update, name='update'),
]

compose/urls.py
from django.urls import path

from . import views

app_name = 'compose'

urlpatterns = [
    path('', views.index, name='index'),
    path('archive/<int:year>/<int:month>/<int:day>', views.archive,
        name='archive'),

    path('login', views.login, name='login'),
    path('login/', views.login, name='login'),
    path('logout', views.logout, name='logout'),
]

writingstreak/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('compose.urls')),
    path('api/', include('api.urls')),
]

compose/models.py
import datetime
import re

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class DailyEntryManager(models.Manager):
    def today(self, *, user):
        """Retrieve today's entry for the given user. If no entry exists,
        create one with the word count goal set to the same goal as the most
        recent entry for that user.
        """
        today = datetime.date.today()
        try:
            return self.get(user=user, date=today)
        except DailyEntry.DoesNotExist:
            try:
                most_recent = self.filter(user=user).latest('date')
            except DailyEntry.DoesNotExist:
                return self.create(date=today, user=user)
            else:
                return self.create(date=today, user=user,
                    word_count_goal=most_recent.word_count_goal)


class DailyEntry(models.Model):
    date = models.DateField()
    text = models.TextField(blank=True)
    word_count = models.IntegerField()
    word_count_goal = models.IntegerField(default=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    objects = DailyEntryManager()

    class Meta:
        verbose_name_plural = 'daily entries'
        ordering = ('-date',)

    def save(self, *args, **kwargs):
        self.word_count = self.calculate_word_count()
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        kwargs = {
            'year': self.date.year,
            'month': self.date.month,
            'day': self.date.day
        }
        return reverse('compose:archive', kwargs=kwargs)

    # Split on whitespace and more than one dash.
    regex = re.compile(r'\s+|--+')
    def calculate_word_count(self):
        return sum(1 for w in self.regex.split(self.text) if w)

    def text_as_html(self):
        return '<p>' + '</p><p>'.join(self.text.splitlines()) + '</p>'

    def __str__(self):
        prefix = '{}, {}'.format(self.user, self.date.isoformat())
        if self.text:
            return prefix + ' ({}...)'.format(self.text[:40])
        else:
            return prefix


def get_current_streak(user):
    """Get the length of the user's current streak, not including today."""
    last_date = datetime.date.today()
    entries = DailyEntry.objects.filter(user=user, date__lt=last_date) \
        .order_by('-date')

    count = 0
    for entry in entries:
        # Exit early for skipped days and for days below the word count goal.
        if last_date - entry.date != datetime.timedelta(1):
            break
        elif entry.word_count < entry.word_count_goal:
            break
        count += 1
        last_date = entry.date
    return count


def get_longest_streak(user):
    """Get the length of the user's longest streak."""
    entries = DailyEntry.objects.filter(user=user).order_by('-date')

    count = 1
    longest = 0
    last_date = datetime.date.today() + datetime.timedelta(1)
    for entry in entries:
        # Exit early for skipped days and for days below the word count goal.
        if last_date - entry.date != datetime.timedelta(1):
            longest = max(count, longest)
            count = 1
        elif entry.word_count < entry.word_count_goal:
            longest = max(count, longest)
            count = 1
        else:
            count += 1
        last_date = entry.date
    return max(count, longest)

api/views.py
import datetime
import json

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect

from compose.models import DailyEntry, get_current_streak, get_longest_streak


@login_required
def fetch(request):
    today = datetime.date.today()
    user = request.user

    entry = DailyEntry.objects.today(user=user)
    total_word_count = sum(e.word_count
        for e in DailyEntry.objects.filter(user=user, date__lt=today))
    word_count_this_month = sum(e.word_count
        for e in DailyEntry.objects.filter(user=user, date__month=today.month))
    response = {
        'longest_streak': get_longest_streak(user),
        'streak_length': get_current_streak(user),
        'text': entry.text,
        'total_word_count': total_word_count,
        'word_count': entry.word_count,
        'word_count_goal': entry.word_count_goal,
        'word_count_this_month': word_count_this_month,
    }
    return JsonResponse(response)


@login_required
def update(request):
    if request.method == 'POST':
        try:
            obj = json.loads(request.body.decode('utf-8'))
        except (json.JSONDecodeError, UnicodeDecodeError):
            return HttpResponse(status_code=400)

        text = obj.get('text')
        word_count_goal = obj.get('word_count_goal')

        entry = DailyEntry.objects.today(user=request.user)
        if text is not None:
            entry.text = text
        if word_count_goal is not None:
            entry.word_count_goal = word_count_goal
        entry.save()
        return HttpResponse()
    else:
        return redirect('compose:index')

compose/views.py
import datetime
import itertools

from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import get_object_or_404, redirect, render

from .models import DailyEntry, get_current_streak


@login_required
def index(request):
    past_entries_by_month = get_past_entries_by_month(request.user)
    context = {
        'past_entries_by_month': past_entries_by_month,
        'user': request.user,
    }
    return render(request, 'compose/index.html', context)


def get_past_entries_by_month(user, *, exclude=None):
    """Return a list of (month, entries) pairs in reverse chronological order,
    where `month` is the month and year as a string and `entries` is a list of
    DailyEntry objects, also in reverse chronological order.
    """
    past_entries = DailyEntry.objects \
        .filter(date__lt=datetime.date.today(), user=user) \
        .exclude(date=exclude) \
        .exclude(word_count=0) \
        .order_by('-date')
    key = lambda e: (e.date.month, e.date.year)
    return [month(g) for _, g in itertools.groupby(past_entries, key)]


def month(entrygroup):
    entrygroup = list(entrygroup)
    return (entrygroup[0].date.strftime('%B %Y'), entrygroup)


@login_required
def archive(request, year, month, day):
    date = datetime.date(year, month, day)
    entry = get_object_or_404(DailyEntry, date=date, user=request.user)
    past_entries_by_month = get_past_entries_by_month(request.user,
        exclude=date)
    context = {
        'entry': entry,
        'past_entries_by_month': past_entries_by_month,
        'user': request.user
    }
    return render(request, 'compose/archive.html', context)


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect(request.POST['next'] or '/')
        else:
            blank_form = AuthenticationForm()
            context = {
                'form': blank_form,
                'errormsg': 'Invalid username or password',
            }
            return render(request, 'compose/login.html', context)
    else:
        if request.user.is_authenticated:
            return redirect('/')

        form = AuthenticationForm()
        context = {
            'form': form,
            'next': request.GET.get('next')
        }
        return render(request, 'compose/login.html', context)


def logout(request):
    auth.logout(request)
    return redirect('compose:login')

compose/templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Writing Streak{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'compose/css/base.css' %}">

    {% block extrahead %}
    {% endblock %}
  </head>

  <body>
    {% block content %}
    {% endblock %}
  </body>
</html>

compose/templates/compose/archive.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{ entry.date }} | Writing Streak{% endblock %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'compose/css/archive.css' %}">
{% endblock %}

{% block content %}
<div class="container">
  <ul class="account-menu">
    <li>{{ user.username }}</li>
    <li><a href="{% url 'compose:index' %}">home</a></li>
    {% if user.is_staff %}<li><a href="{% url 'admin:index' %}" target="_blank">admin</a></li>{% endif %}
    <li><a href="{% url 'compose:logout' %}">logout</a></li>
  </ul>

  <h2>{{ entry.date }}</h2>
  {% autoescape off %}
  <div id="archive-text">{{ entry.text_as_html }}</div>
  {% endautoescape %}

  <h3>Other entries</h3>
  {% include 'compose/pastentries.html' %}
</div>
{% endblock %}

compose/templates/compose/index.html
{% extends 'base.html' %}

{% load static %}

{% block extrahead %}
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>

<link rel="stylesheet" href="{% static 'compose/css/index.css' %}">
{% endblock %}

{% block content %}
<div class="container">
  {% csrf_token %}

  <ul class="account-menu">
    <li>{{ user.username }}</li>
    {% if user.is_staff %}<li><a href="{% url 'admin:index' %}" target="_blank">admin</a></li>{% endif %}
    <li><a href="{% url 'compose:logout' %}">logout</a></li>
  </ul>

  <!-- Root of the main React component (see frontend/index.js) -->
  <div id="react-root"></div>

  <h3>Past entries</h3>
  {% include 'compose/pastentries.html' %}
</div>

<script src="{% static 'bundle.js' %}"></script>
{% endblock %}

compose/templates/compose/login.html
{% extends 'base.html' %}

{% block title %}Login | Writing Streak{% endblock %}

{% block content %}
<div class="container">
  {% if errormsg %}
  <p>{{ errormsg }}</p>
  {% endif %}

  <form method="post" action="{% url 'compose:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="next" value="{{ next|default_if_none:"/" }}" />
    <input id="submit" type="submit" value="Log in" />
  </form>
</div>
{% endblock %}

compose/templates/compose/pastentries.html
{% load humanize %}

<ul class="past-writing-list">
  {% for month, past_entries in past_entries_by_month %}
  <li>{{ month }}</li>
  <ul>
  {% for past_entry in past_entries %}
  <li><a href="{{ past_entry.get_absolute_url }}">{{ past_entry.date }}</a>
    ({{ past_entry.word_count|intcomma }} word{{ past_entry.word_count|pluralize }})
  </li>
  {% endfor %}
  </ul>
  {% empty %}
  <li>No writing yet!</li>
  {% endfor %}
</ul>

writingstreak/templates/base.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Writing Streak{% endblock %}</title>

    <!-- Pure CSS -->
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css"
      integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w"
      crossorigin="anonymous">

    {% block extrahead %}
    {% endblock %}
  </head>

  <body>
    {% block content %}
    {% endblock %}
  </body>
</html>